services:
  app:
    build:
      context: .
    image: my-php-app:latest
    container_name: php-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${USER}
      - PASS=${PASS}
  web-ui:
    build:
      context: "./Web UI/"
    image: web-ui
    container_name: web_ui
    ports:
      - 4173:4173
    environment:
      - VITE_API_HOST=http://app:8000
  db:
    image: mysql:8.0
    container_name: mysql-db
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_TCP_PORT: ${PORT}
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
volumes:
  db_data:
